<a href="https://colab.research.google.com/github/younghwangit/mulcamp34/blob/main/NumPy20241003.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np #NumPy 라이브러리 불러오기
print(np.__version__)

1.26.2


In [ ]:
num1 = [1 ,2, 3, 4]
num2 = [3, 4, 5, 6]

num1 + num2 #배열끼지의 합이 어려움

[1, 2, 3, 4, 3, 4, 5, 6]

In [ ]:
arr1 = np.array(num1)
arr2 = np.array(num2)
arr1

array([1, 2, 3, 4])

In [ ]:
arr2

array([3, 4, 5, 6])

In [ ]:
arr1 + arr2 #배열끼리의 합산이 가능함

array([ 4,  6,  8, 10])

In [ ]:
data1 = [0, 1, 2, 3, 4, 5,]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

In [ ]:
a1.dtype #출력: int32 #비트단위로 출려됨

dtype('int32')

In [ ]:
np.array([0.5, 2, 0.01, 8]).dtype #출려기 float64

dtype('float64')

In [ ]:
#Numpy 배열 생성

In [ ]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [ ]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(10) #1차원 배열을 2차원 또는 3차원으로 변경

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(12).reshape(4 ,3) #12 = 4 * 3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.arange(12).reshape(4, 5) #12 != 4 * 5

ValueError: cannot reshape array of size 12 into shape (4,5)

In [ ]:
np.arange(12).reshape(2, 2, 3) #3차원으로 배열 변경. #12 = 2 * 2 * 3

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [ ]:
b1 = np.arange(12).reshape(2, 2, 3)
b1.shape #3차원임으로 확인

(2, 2, 3)

In [ ]:
b1 = np.arange(12).reshape(4, 3)
b1.shape

(4, 3)

In [ ]:
b2 = np.arange(5)
b2.shape #1차원 배열

(5,)

In [ ]:
#범위의 시작과 끝 정하기 배열 생성
np.linspace(0, 10, 5) #0과 10인덱스 사이의 범위에서 균일한 간격의 5개의 값을 생성

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.linspace(0, np.pi, 20) #0부터 3.14... 사이에 20개의 값을 생성

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones((2, 2, 2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [ ]:
#단위행렬
arrI = np.eye(3)
arrI

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arrI.shape

(3, 3)

In [ ]:
np.array(["1.5", "0.62"]) #문자열 데이터

array(['1.5', '0.62'], dtype='<U4')

In [ ]:
#astype() #데이터 형변환
arr = np.array(["1.5", "0.62"])
numArr = arr.astype(float)
numArr.dtype

dtype('float64')

In [ ]:
numF1 = np.array([10, 21, 0.549, 4.75, 5.98])
numF1 = numF1.astype(int)
numF1 #출력값이 소숫점 아래를 버린 형태로 나온다

array([10, 21,  0,  4,  5])

In [ ]:
numF1 = np.array([10, 21, 0.549, 4.75, 5.98])
numF1 = numF1.astype(float)
numF1 #온전한 형태로 출력

array([10.   , 21.   ,  0.549,  4.75 ,  5.98 ])

In [ ]:
# p.224
# 난수 무작위로 숫자를 추출

np.random.rand(2, 3) #0~1 사이의 실수 난수를 추출 후 2와 3 배열로 출력

array([[0.29901909, 0.77302287, 0.23787034],
       [0.57389386, 0.33086562, 0.4192384 ]])

In [ ]:
np.random.rand(3, 2)

array([[0.4646088 , 0.93267417],
       [0.93907847, 0.94383621],
       [0.32547933, 0.13151019]])

In [ ]:
np.random.randint(1, 100, 10) #1과 100 인덱스 사이에 10개의 값을 무작위로 추출

array([19, 62, 15, 39, 41,  8, 93, 29,  3, 63])

In [ ]:
#미션: 로또번호생성기 #로또번호는 번호가 중복되면 안 된다

In [ ]:
np.random.randint(1, 100, 10)

array([ 4, 99, 20, 15, 30, 89, 74, 91, 74, 86])

In [ ]:
randNum = np.random.choice(np.arange(1, 100), size = 10, replace =False)
sortedRandNum = np.sort(randNum)
print(sortedRandNum)

[ 7  8 26 36 46 58 61 64 81 84]


In [ ]:
#조원의 로또번호생성기

numbers = np.random.choice(range(6, 45), size=6, replace=False)
print(numbers)

[13  9 21 14 15 11]


In [ ]:
#강사님 코드
import random

def generate_lotto_numbers():
    """
    1부터 45까지의 숫자 중 무작위로 6개를 선택하여 로또 번호를 생성합니다.
    이 때, 중복된 숫자가 없도록 합니다.
    """
    lotto_numbers = set()

    while len(lotto_numbers) < 6:
        number = random.randint(1, 45)
        lotto_numbers.add(number)

    return sorted(lotto_numbers)

# 로또 번호 생성
lotto_numbers = generate_lotto_numbers()
print("생성된 로또 번호:", lotto_numbers)

생성된 로또 번호: [8, 14, 20, 29, 31, 39]


In [ ]:
# p225 ~
# 배열의 연산

#통계를 위한 연산

#합 평균 표준편차 분산 최솟값 최댓값 누적합, 누적합, 누적곱 메서드가 존재한다.
#기술통게량: 현재 데이터 상태를 표현하는 Descriptive Statisstics

#통계: 모수 통계, 비모수 통계, 베이지안 통계

In [ ]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [ ]:
arr3.sum()

10

In [ ]:
arr3.mean()

2.0

In [ ]:
arr3.std() #표준편차

1.4142135623730951

In [ ]:
arr3.var() #분산

2.0

In [ ]:
#행렬연산
- 선형대수(Linea Algebra)

In [ ]:
A = np.array([0, 1, 2, 3]).reshape(2, 2)
A

array([[0, 1],
       [2, 3]])

In [ ]:
B = np.array([3, 2, 0, 1]).reshape(2, 2)
B

array([[3, 2],
       [0, 1]])

In [ ]:
A.dot(B)

array([[0, 1],
       [6, 7]])

In [ ]:
A.transpose() #전치행렬

array([[0, 2],
       [1, 3]])

In [ ]:
np.linalg.inv(A) #역행

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [ ]:
## 배열의 인덱싱과 슬라이싱
a1 = np.array([0, 10, 20, 30, 40, 50])
a1

array([ 0, 10, 20, 30, 40, 50])

In [ ]:
a1[0]

0

In [ ]:
a1[-1] = 70
a1

array([ 0, 10, 20, 30, 40, 70])

In [ ]:
#리스트 통한 추출
a1[[0, 2, 4]] #대괄호가 2개 [ [ ] ]

array([ 0, 20, 40])

In [ ]:
idxList = [0, 2, 4]
a1[idxList] #덜 헷갈리는 방

array([ 0, 20, 40])

In [ ]:
a2 = np.arange(10, 100, 10).reshape(3, 3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
"""
2차원 배월의 인덱스 위치
0 1 2
1
2
배열[세로, 가로]
"""

print(a2[0, 2])
print(a2[1,1])
print(a2[2, 1])

30
50
80


In [ ]:
a2[2,2] = 95
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

In [ ]:
a2[1,0] = 45
a2

array([[10, 20, 30],
       [45, 50, 60],
       [70, 80, 95]])

In [ ]:
a2[1]

array([45, 50, 60])

In [ ]:
a2[1] = [50, 55, 65] #야메
a2

array([[10, 20, 30],
       [50, 55, 65],
       [70, 80, 95]])

In [ ]:
a2[0] = np.array([1, 2, 3]) #정석대로
a2

array([[ 1,  2,  3],
       [50, 55, 65],
       [70, 80, 95]])

In [ ]:
#2차원 배열의 행과 열 위치 지장해서 원소 추출

a2[[0,2],[0, 1]] #(행의 위치 1, 열의 위치 1)/(행의 위치 2, 열의 위치 2)

array([ 1, 80])

In [ ]:
a2[0, 0], a2[2, 1] #위와 동일

(1, 80)

In [ ]:
a2[0,2], a2[0,1] #이게 아님!!

(3, 2)

In [ ]:
#배열 조건문
# pandas 문법과 유사하다

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
 [a>3]

[array([False, False, False,  True,  True,  True])]

In [ ]:
a[a>3] #행 추출. 조건에 맞는 True값만 추출함

array([4, 5, 6])

In [ ]:
a % 2 == 0 #실무에서는 이런 코드를 작성하는 것이 핵심이다.

array([False,  True, False,  True, False,  True])

In [ ]:
a[a % 2 == 0]

array([2, 4, 6])

In [ ]:
#배열의 슬라이싱
b1 = np.array([0, 1, 2, 3, 4, 5])
b1[1:4]

array([1, 2, 3])

In [ ]:
print(b1[:3])
print(b1[2:])

[0 1 2]
[2 3 4 5]


In [ ]:
b1[0:4:2] #이거 뭐였지?

array([0, 2])

In [ ]:
b1[2:5] = np.array([25, 35, 45])
b1

array([ 0,  1, 25, 35, 45,  5])

In [ ]:
b1[3:6] = 60 #하나의 값으로 통일
b1

array([ 0,  1, 25, 60, 60, 60])

In [ ]:
b2 = np.arange(10, 100, 10).reshape(3, 3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
b2[1:3, 1:3] #행: 1부터 2까지(인덱스 3미만). 열: 1부터 2까지

array([[50, 60],
       [80, 90]])

In [ ]:
nums = [1, 2, 3, ["a","b"]] #중첩리스트
nums[3][0]

'a'

In [ ]:
print(b2[1])
print(b2[1][0:2])

[40 50 60]
[40 50]


In [ ]:
## NumPy 조건문
# np.where:  단일 조건문
# np.select: 다중 조건문

In [ ]:
arr  = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 0, 1, 2, 3, 4, 50, 60, 40, 70, 80, 90
np.where(arr < 5, arr, arr * 10)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [ ]:
arr =np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 100, 101, 2, 3, 4, 5, 12, 14, 16, 18
# 2 미만은 100 더하기
# 5 초과일 때는 2를 곱한다
comd_list = [arr>5, arr <2]
choiceList = [arr * 2, arr + 100]

np.select(comd_list, choiceList, default = arr)

array([100, 101,   2,   3,   4,   5,  12,  14,  16,  18])